### PR TITLE
Track OpenJDK 21 in openJDKFeed.sh

### PR DESCRIPTION
**Pull request by shakuzen**
# Description
Adds 21 that was missing.

# Reasons
A new version of 21 (21.0.1) has been available since October 28, 2023 but hasn't been released.

# Checklist

Please check through the following before opening your PR. Thank you!

- [ ] I have made changes to the `Dockerfile.template` file only
- [x] I have not made any manual changes to automatically generated files
- [ ] My PR follows best practices as described in the [contributing guidelines](CONTRIBUTING)
- [x] (Optional, but recommended) My commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

**Comment by shakuzen** [comment]
I don't have access to see the logs to know why the build is failing. Could someone from the team with access take a look or otherwise review why 21 is missing from the configuration?

**Comment by JalexChen** [comment]
hello @shakuzen - thanks for submitting this PR. we certainly appreciate it. i was able to build a test image for this, however, it seems like mill was not being updated correctly. #189 fixes this, so once that has been merged in, would you mind rebasing and i'll approve and  merge your PR?

the build itself is failing because only maintainers can run builds, and 21 was not initially included because it was so new and there were some issues that needed to be sorted

**Comment by shakuzen** [comment]
@JalexChen thank you for taking a look. I've rebased the pull request on `main`.

**Review by JalexChen — APPROVED** [review]
LGTM

**Pull request merged**
