### PR TITLE
Respin browsers tags for xvfb. [release]

### PR DESCRIPTION
**Pull request by felicianotech**

### CODE REVIEW

**Review by dsayling — COMMENTED** [review]
Looks like this one didn't get the xvfb change

**Comment by felicianotech** [comment]
@dsayling That's because I did this one incorrectly. I forgot to remove the local variant copy. Good catch. I'll get this fixed and updated.

**Comment by felicianotech** [comment]
Rerequesting review. This is now ready.

**Comment by felicianotech** [comment]
@dsayling bump :)

**Review by dsayling — APPROVED** [review]
Sorry - distracted

**Pull request merged**
