### PR TITLE
Update readme with correct information

### PR DESCRIPTION
**Pull request by jonatan-ivanov**

### CODE REVIEW

**Comment by felicianotech** [comment]
Thank you but this was covered in #77 and #80.

**Comment by jonatan-ivanov** [comment]
@felicianotech 👍🏼 
You might still want to take a look at the readme changes in this PR. :)

**Comment by felicianotech** [comment]
Yeah I saw them. If you want to rebase your PR I can reopen it so I can pull in those changes specifically.

**Comment by felicianotech** [comment]
Looks great. Thank you!

**Pull request merged**
